services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hackathon_web
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
